services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: grailsuser
      POSTGRES_PASSWORD: grailspassword
      POSTGRES_DB: grailsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
