name: Grails CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # Use Zulu JDK as per your project's requirement
        java-version: '11'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Install SDKMAN and Grails
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install grails 4.1.3
        sdk use grails 4.1.3

    - name: Build project
      run: ./gradlew assemble

    - name: Run tests
      run: ./gradlew test

    - name: Upload test report
      if: always()  # Ensures it runs even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: Test Report
        path: build/reports/tests/test/
